flash_cards_app/urls.py
from django.urls import path
#from django.conf.urls import url
from flash_cards_app import views
from flash_cards_app.models import Card

# home_list_view = views.HomeListView.as_view(
#     queryset=Card.objects.order_by("front")[:5],
#     context_object_name="card_list",
#     template_name="flashcards/home.html",
# )
urlpatterns = [
    # path("", views.home, name="home"),
    path("", views.deck, name="decks"),
    path("about/", views.about, name="about"),
    path('card_delete/<int:id>', views.card_delete, name='card_delete'),
    path('deck_delete/<int:id>', views.deck_delete, name='deck_delete'),
    path('view_deck/<int:id>', views.view_deck, name="view_deck"),
    path('card_list/<int:id>', views.card_list, name="card_list"),
    path('card_Edit/<int:id>', views.card_Edit, name="card_Edit"),
    path('card_New/<int:id>', views.card_New, name='card_New'),
    path('carousel', views.carousel, name='carousel'),
    path('deck_new/', views.deck_new, name="deck_new"),
    path('deck_edit/<int:id>', views.deck_edit, name='deck_edit'),
    path('deck_list/', views.deck_list, name="deck_list"),
    path('card_test/<int:id>', views.card_test, name="card_test"),
]

flashcards/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("flash_cards_app.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

flash_cards_app/models.py
from django.db import models
from django_quill.fields import QuillField

# Create your models here.
class Deck(models.Model):
    name = models.CharField(max_length=300)


class Card(models.Model):
    card_num = models.IntegerField()
    front = models.CharField(max_length=300)
    front_content = QuillField()
    back = models.CharField(max_length=300)
    back_content = QuillField()
    card_image = models.ImageField(upload_to = 'upload/')
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)

    displayFirst = ""

flash_cards_app/forms.py
from django import forms
from django import forms
from flash_cards_app.models import Card, Deck

class CardForm(forms.ModelForm):
    
    card_image = forms.ImageField(required=False)
    clear_card_image = forms.BooleanField(required=False)

    class Meta:
        model = Card
        fields = ("front_content", "back_content", 'card_image',)

class DeckForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = ("name",)

class TestCardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ("front_content",)

flash_cards_app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.utils.timezone import datetime
from flash_cards_app.forms import CardForm, DeckForm, TestCardForm
from flash_cards_app.models import Card, Deck
from django.views.generic import ListView
#from django.db.models import Max
# Create your views here.

app_name = 'flash_cards'

def home(request):
    form = CardForm(request.POST or None)
    cards = Card.objects.all()
    return render(request, "flashcards/home.html", {"form": form, "card_list": cards})


def about(request):
    return render(request, "flashcards/about.html")

def card_delete(request, id):
    card = Card.objects.get(id=id)
    deck = card.deck
    card.delete()
    #Renumber the remaining cards
    cardList = Card.objects.filter(deck=deck).order_by('card_num')
    for i in range(0, len(cardList)):
        cardList[i].card_num = i+1
        cardList[i].save()

    return redirect("view_deck", card.deck.id)

def deck(request):
    form = DeckForm(request.POST or None)
    decks = Deck.objects.all()

    if request.method == "POST":
        if form.is_valid():
            message = form.save(commit=False)
            message.save()
            return redirect("decks")

        else:
            return render(request, "flashcards/deck.html", {"form": form, "deck_list": decks})
    
    else:
        return render(request, "flashcards/deck.html", {"form": form, "deck_list": decks})

def deck_delete(request, id):
    deck = Deck.objects.get(id=id)
    deck.delete()
    return redirect("decks")

def view_deck(request, id):
    deck = Deck.objects.get(id=id)
    card_list = Card.objects.filter(deck=deck)
    if card_list.count() > 1:
        starting_card = card_list[0]
    else:
        starting_card = None

    form = CardForm(request.POST or None, request.FILES or None)
    request.META.get('HHTP_CUSTOM_HEADER')
    if request.method == "POST":
        if form.is_valid():
            card = form.save(commit=False)
            card.deck = deck
            card.save()
            return redirect("view_deck", id=id)

        else:
            return render(request, "flashcards/view_deck.html", {"deck": deck, "card_list": card_list, "form": form, "starting_card": card_list[0]})
    
    else:
        return render(request, "flashcards/view_deck.html", {"deck": deck, "card_list": card_list, "form": form, "starting_card": starting_card})

def card_list(request, id):
    deck = Deck.objects.get(id=id)
    card_list = Card.objects.filter(deck = deck)
    return render(request, "flashcards/card_list.html", { "card_list": card_list })

def card_Edit(request, id):
    card = Card.objects.get(id=id)
    if request.method == "POST":
        #deck = card.deck
        #card_list = Card.objects.filter(deck=deck)
        form = CardForm(request.POST, request.FILES or None, instance=card)
        
        if form.is_valid():
            #clearImage = form.cleaned_data['clear_card_image']
            if form.cleaned_data['clear_card_image'] == True:
                #card.card_image = ''
                card.card_image = None
            form.save()
            
            return HttpResponse(status=204, headers={'HX-Trigger': 'cardListChanged'})
            #return render(request, "flashcards/view_deck.html", {"deck": deck, "card_list": card_list, "form": form, "starting_card": card})
    else:
        form = CardForm(instance=card)

    return render(request, "flashcards/card_newEdit.html", {"form": form, "card": card, "deck": card.deck, "isNew": False})

def card_New(request, id):
    deck = Deck.objects.get(id=id)
    form = CardForm(request.POST or None, request.FILES or None)
    isNew = True
    if request.method == "POST":
        if form.is_valid():
            card = form.save(commit=False)

            cardList = Card.objects.filter(deck=deck)
            if cardList.count() > 0:
                #maxCardNum = cardList.aggregate(Max('card_num'))
                maxCardNum = Card.objects.filter(deck=deck).order_by('-id')[0].card_num
            else:
                maxCardNum = 0

            card.deck = deck
            card.card_num = maxCardNum + 1
            card.save()
            return HttpResponse(status=204, headers={'HX-Trigger': 'cardListChanged'})
        else:
            isNew = False

    return render(request, "flashcards/card_newEdit.html", {"form": form, "deck": deck, "isNew": isNew})

def carousel(request):
    return render(request, "flashcards/carousel.html")

def deck_new(request):
    form = DeckForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponse(status=204, headers={'HX-Trigger': 'deckListChanged'})
    return render(request, "flashcards/deck_newEdit.html", {"form": form })

def deck_edit(request, id):
    deck = Deck.objects.get(id=id)
    if request.method == "POST":
        form = DeckForm(request.POST, instance=deck)
        if form.is_valid():
            form.save()
            return HttpResponse(status=204, headers={'HX-Trigger': 'deckListChanged'})
    else:
        form = DeckForm(instance=deck)

    #Show view on first click; or if form isn't valid, return the popup page with errors
    return render(request, "flashcards/deck_newEdit.html", {"form": form, "deck": deck})

def deck_list(request):
    deck_list = Deck.objects.all()
    deck_list_chunks = [deck_list[i: i+2] for i in range(0, len(deck_list), 2)]
    return render(request, "flashcards/deck_list.html", {"deck_list_chunks": deck_list_chunks})


def card_test(request, id):
    return render(request, "flashcards/card_test.html", {'form': TestCardForm()})

flash_cards_app/templates/flashcards/about.html
{% extends "flashcards/layout.html" %}
{% block title %}
<p>About Us</p>
{% endblock %}
{% block content %}
<p>Just another about page</p>
{% endblock %}

flash_cards_app/templates/flashcards/card_list.html
{% if card_list %}
<div class="carouselContainer">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" data-interval="false">
        <div class="carousel-inner">
        {% for card in card_list %}
        <div class="flashcard-header mx-auto" id="card-header{{card.id}}">
            <div class="row">
                <div class="col">
                </div>
                <div class="col d-flex justify-content-center align-items-center">
                    <span class="card-num">{{ card.card_num }}/{{ card_list.count }}</span>
                </div>
                <div class="col d-flex justify-content-end align-items-center">
                    <button hx-get="{% url 'card_Edit' id=card.id %}"
                        hx-target="#dialog"
                        onclick="setCard({{ card.id }}, event)"
                        class="btn btn-with-fa"
                        style="z-index: 1000;">
                        <i class="fa-solid fa-pen-to-square"></i>Edit
                    </button>
                </div>
            </div>
        </div>
        
            <div class="carousel-item" style="height: 400px;" id="carousel-item{{ card.id }}">
                <div class="flip-card" id="flashCard{{ card.id }}">
                    <div class="flip-card-inner">
                        <div class="flip-card-front" onclick="flipCard({{ card.id }})">

                            <p class="flip-card-text"> {{ card.front_content.html|safe }} </p>
                            {% if card.card_image.url != Null %}
                            <img src="{{ card.card_image.url }}" height="150">
                            {% endif %}
                            
                        </div>
                        <div class="flip-card-back" onclick="flipCard({{ card.id }})">
                            <p class="flip-card-text"> {{ card.back_content.html|safe }} </p>
                                
                        </div>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>

        <button class="carousel-control-prev-custom" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev" onclick="prevCard()">
        {% comment %} <span class="carousel-control-prev-icon" aria-hidden="true"></span> {% endcomment %}
        <i class="fa-solid fa-chevron-left fa-lg"></i>
        <span class="visually-hidden"></span>
        </button>
        <button class="carousel-control-next-custom" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next" onclick="nextCard()">
        {% comment %} <span class="carousel-control-next-icon" aria-hidden="true"></span> {% endcomment %}
        <i class="fa-solid fa-chevron-right fa-lg"></i>
        <span class="visually-hidden"></span>
        </button>

    </div>
</div>
{% else %}
<p>Add a new card!</p>
{% endif %}

<script>

    function prevCard(id) {
        $('#carouselExampleControls').carousel('prev')

        //Get all header elements
        var allHeaders = document.getElementsByClassName('flashcard-header')
        //Find the active header
        activeHeader = document.getElementsByClassName('header-active')
        //Find the active header index within the array of all header elements
        var foundHeader = Array.from(allHeaders).find(element => element.id==activeHeader[0].id)
        var foundHeaderIndex = (Array.from(allHeaders)).indexOf(foundHeader)
        //Add the header-active class to the previous header element
        if (foundHeaderIndex != 0) {
            foundHeader.classList.remove("header-active")
            allHeaders[foundHeaderIndex-1].classList.add("header-active")
        }
        //If it's the first element, add it to the last element
        else {
            foundHeader.classList.remove("header-active")
            allHeaders[allHeaders.length-1].classList.add("header-active")
        }

    }

    function nextCard(id) {
        $('#carouselExampleControls').carousel('next')

        //Get all header elements
        var allHeaders = document.getElementsByClassName('flashcard-header')
        //Get the active header element
        activeHeader = document.getElementsByClassName('header-active')
        //Find the active header element index in the allHeaders list
        var foundHeader = Array.from(allHeaders).find(element => element.id==activeHeader[0].id)
        var foundHeaderIndex = (Array.from(allHeaders)).indexOf(foundHeader)
        //Make the next element in the list the active element
        if (foundHeaderIndex != allHeaders.length-1) {
            foundHeader.classList.remove("header-active")
            allHeaders[foundHeaderIndex+1].classList.add("header-active")
        }
        //If the current element is the last one, make the first one active
        else {
            foundHeader.classList.remove("header-active")
            allHeaders[0].classList.add("header-active")
        }

    }

    function setCard(id, event) {
        localStorage.setItem('currentCard', id)
        //console.log(localStorage.getItem('currentCard'))
        event.stopPropagation();
    }

    $(document).ready(function() {
        //console.log("Hello World")
        //console.log(localStorage.getItem("currentCard"))
        if(localStorage.getItem("currentCard") != null) {
            
            var currentCard = localStorage.getItem("currentCard");
            var docCard = document.getElementById("carousel-item"+currentCard);
            var cardHeader = document.getElementById("card-header"+currentCard);
            console.log(docCard)
            if (docCard != null) {
                docCard.classList.add("active");
                cardHeader.classList.add("header-active")
            }
            else {
                var docCards = document.getElementsByClassName("carousel-item")
                docCards[0].classList.add("active");
                var cardHeaders = document.getElementsByClassName("flashcard-header")
                cardHeaders[0].classList.add("header-active")
            }
            //console.log(currentCard + " " + docCard.classList)
        }
        else {
            var docCards = document.getElementsByClassName("carousel-item")
            docCards[0].classList.add("active");
            var cardHeaders = document.getElementsByClassName("flashcard-header")
            cardHeaders[0].classList.add("header-active")
        }
    })
</script>

flash_cards_app/templates/flashcards/card_newEdit copy.html
<div class="modal-content">
    <div class="modal-header">
        {% if isNew %}
        <h2>Create a Card</h2>
        {% else %}
        <h2>Edit Card</h2>
        {% endif %}
    </div>

    <form hx-post="{{ request.path }}" enctype="multipart/form-data" class="log-form">

    <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.front.id_for_label }}">Front</label>
                <input
                    type="text"
                    class="form-control"
                    id="{{ form.front.id_for_label }}"
                    name="front"
                    {% if isNew is False %}
                    value="{{ form.front.value }}"
                    {% endif %}
                />
                {{ form.errors.front }}
                <label = for="{{ form.front_content.id_for_label }}">Front Conent</label>
                {{ form.front_content }}
                <label for="{{ form.back.id_for_label }}">Back</label>
                <input
                    type="text"
                    class="form-control"
                    id="{{ form.back.id_for_label }}"
                    name="back"
                    {% if isNew is False %}
                    value="{{ form.back.value }}"
                    {% endif %}
                />
                {{ form.errors.back }}
                <label for="{{ form.card_image.id_for_label }}">Image</label><br>
                {% if card.card_image %}
                <img src={{ form.instance.card_image.url }} height="70px"><br>
                <input
                    type="checkbox"
                    name="clear_card_image"
                    id="{{ form.clear_card_image.id_for_label }}"
                >Clear</label>
                <br>
                <span>Change:<span><br>
                {% endif %}
                <div class="input-group">
                    <div class="custom-file custom-file-no-browse-btn">
                        <input
                            type="file"
                            class="custom-file-input"
                            id="{{ form.card_image.id_for_label }}"
                            name="card_image"
                        >
                        <label class="custom-file-label" for="{{ form.card_image.id_for_label }}">
                            {% if form.instance.card_image %}
                            {{ form.instance.card_image.name }}
                            {% else %}
                            Choose File
                            {% endif %}
                        </label>
                    </div>
                    <div class="input-group-append">
                        <button 
                            class="btn btn-with-fa-upload" 
                            type="button" 
                            id="get_file" 
                            onclick="choose_file()">
                            <i class="fa-solid fa-image"></i>Upload
                        </button>
                    </div>
                </div>
                {{ form.errors.card_image }}    
            </div>
    </div>

    <div class="modal-footer">
        <div class="d-flex w-100">
            {% if isNew is False %}
            <a href="/card_delete/{{card.id}}" class="btn btn-with-fa p-2"><i class="fa-solid fa-trash"></i>Delete</a>
            {% endif %}
            <button type="submit" class="btn btn-with-fa ml-auto p-2">
                {% if isNew %}
                Create
                {% else %}
                Save
                {% endif %}
            </button>
        </div>
    </div>

    </form>

</div>

<script>
    function clearImage() {
        document.getElementById()
    }

    function choose_file() {
        document.getElementById("id_card_image").click();
    }

    $('#id_card_image').change(function() {
        var file = $('#id_card_image')[0].files[0].name;
        console.log(file);
        $('.custom-file-label').text(file);
    });
</script>

flash_cards_app/templates/flashcards/card_newEdit.html
<div class="modal-content">
    <div class="modal-header">
        {% if isNew %}
        <h2>Create a Card</h2>
        {% else %}
        <h2>Edit Card</h2>
        {% endif %}
    </div>

    <form hx-post="{{ request.path }}" enctype="multipart/form-data" class="log-form">

    <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
                <label = for="{{ form.front_content.id_for_label }}">Front</label>
                {{ form.front_content }}
                {{ form.errors.front_content }}
                <label for="{{ form.back_content.id_for_label }}">Back</label>
                {{ form.back_content }}
                {{ form.errors.back_content }}
                <label for="{{ form.card_image.id_for_label }}">Image</label><br>
                {% if card.card_image %}
                <img src={{ form.instance.card_image.url }} height="70px"><br>
                <input
                    type="checkbox"
                    name="clear_card_image"
                    id="{{ form.clear_card_image.id_for_label }}"
                >Clear</label>
                <br>
                <span>Change:<span><br>
                {% endif %}
                <div class="input-group">
                    <div class="custom-file custom-file-no-browse-btn">
                        <input
                            type="file"
                            class="custom-file-input"
                            id="{{ form.card_image.id_for_label }}"
                            name="card_image"
                        >
                        <label class="custom-file-label" for="{{ form.card_image.id_for_label }}">
                            {% if form.instance.card_image %}
                            {{ form.instance.card_image.name }}
                            {% else %}
                            Choose File
                            {% endif %}
                        </label>
                    </div>
                    <div class="input-group-append">
                        <button 
                            class="btn btn-with-fa-upload" 
                            type="button" 
                            id="get_file" 
                            onclick="choose_file()">
                            <i class="fa-solid fa-image"></i>Upload
                        </button>
                    </div>
                </div>
                {{ form.errors.card_image }}    
            </div>
    </div>

    <div class="modal-footer">
        <div class="d-flex w-100">
            {% if isNew is False %}
            <a href="/card_delete/{{card.id}}" class="btn btn-with-fa p-2"><i class="fa-solid fa-trash"></i>Delete</a>
            {% endif %}
            <button type="submit" class="btn btn-with-fa ml-auto p-2">
                {% if isNew %}
                Create
                {% else %}
                Save
                {% endif %}
            </button>
        </div>
    </div>

    </form>

</div>

<script>
    function clearImage() {
        document.getElementById()
    }

    function choose_file() {
        document.getElementById("id_card_image").click();
    }

    $('#id_card_image').change(function() {
        var file = $('#id_card_image')[0].files[0].name;
        console.log(file);
        $('.custom-file-label').text(file);
    });
</script>

flash_cards_app/templates/flashcards/card_test.html
{% extends "flashcards/layout.html" %}
{% block title %}

{% endblock %}
{% block content %}
<form action="" method="POST">{%csrf_token%}
    {{ form.as_p }}
</form>
{% endblock %}

flash_cards_app/templates/flashcards/carousel.html
{% extends "flashcards/layout.html" %}
{% block title %}
Carousel
{% endblock %}
{% block content %}
{% comment %} <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> {% endcomment %}

<style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
    width: 70%;
    margin: auto;
    }
</style>

<p>Testing the carousel</p>

<div class="container">
    <br>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        <div class="item active">
        <img src="media\upload\one_punch_man.jpeg" alt="Chania" width="460" height="345">
        <div class="carousel-caption">
            <h3>Chania</h3>
            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
        </div>
        </div>

        <div class="item">
        <img src="media\upload\pheonix.jpg" alt="Chania" width="460" height="345">
        <div class="carousel-caption">
            <h3>Chania</h3>
            <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
        </div>
        </div>
    
        <div class="item">
        <img src="media\upload\Shaggy_Tommy.jpg" alt="Flower" width="460" height="345">
        <div class="carousel-caption">
            <h3>Flowers</h3>
            <p>Beautiful flowers in Kolymbari, Crete.</p>
        </div>
        </div>

        <div class="item">
        <img src="media\upload\shrek.jpg" alt="Flower" width="460" height="345">
        <div class="carousel-caption">
            <h3>Flowers</h3>
            <p>Beautiful flowers in Kolymbari, Crete.</p>
        </div>
        </div>
    
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
</div>


{% endblock %}

flash_cards_app/templates/flashcards/deck.html
{% extends "flashcards/layout.html" %}
{% block title %}
Decks
{% endblock %}

{% block content %}

<div class="mt-3 mb-4">
    <h2>Welcome to John's Flashcards app!</h2>
    <p>Select a deck below, or create a new deck to get started.</p>
    <button class="btn btn-with-fa" hx-get="{% url 'deck_new' %}" hx-target="#dialog" class="button btn-primary">
        <i class="fa-regular fa-square-plus"></i>New Deck</button>
</div>

<div hx-get="{% url 'deck_list' %}" hx-trigger="load, deckListChanged from:body" hx-target="this">
    <span>...Loading...</span>
</div>

{% endblock %}

flash_cards_app/templates/flashcards/deck_list.html
{% if deck_list_chunks %}  
{% for chunk in deck_list_chunks %}
<div class="row">
    {% for deck in chunk %}
    <div class="col-sm-6">
        <a class="custom_atag" href="{% url 'view_deck' deck.id %}">
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title">{{ deck.name }}</h5>
                <p class="card-text">Cards: {{ deck.card_set.count }}</p>
            </div>
        </div>
        </a>
        <button class="btn btn-with-fa btn-sm card_edit" hx-get="{% url 'deck_edit' id=deck.id %}" hx-target="#dialog" class="button btn-primary"><i class="fa-solid fa-pen-to-square"></i>Edit</button>
    </div>
    {% endfor %}
</div>
{% endfor %}
{% else %}
<p>No decks yet</p>
{% endif %}

flash_cards_app/templates/flashcards/deck_newEdit.html
<div class="modal-content">
    <div class="modal-header">
        {% if deck %}
        <h2>Edit Deck</h2>
        {% else %}
        <h2>Create Deck</h2>
        {% endif %}
    </div>

    <form hx-post="{{ request.path }}" enctype="multipart/form-data" class="log-form" id="deck_form">

    <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Deck Name</label>
                <input
                    type="text"
                    class="form-control"
                    id="{{ form.name.id_for_label }}"
                    name="name"
                    {% if form.instance.name %}
                    value="{{ form.name.value }}"
                    {% endif %}
                />
                {{ form.errors.name }}
            </div>

    </div>

    <div class="modal-footer">
        <div class="d-flex align-items-center w-100">
            {% if deck %}
            <a href="/deck_delete/{{ deck.id }}" class="btn btn-with-fa p-2"><i class="fa-solid fa-trash"></i>Delete</a>
            {% endif %}
            <button type="submit" class="btn btn-with-fa p-2 ml-auto">Save</button>
        </div>
    </form>

    </div>
</div>

flash_cards_app/templates/flashcards/home.html
{% extends "flashcards/layout.html" %}
{% block title %}
<p>Just another home page</p>
{% endblock %}
{% block content %}
    {% comment %} <form method="POST" class="log-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form> {% endcomment %}

    <h2>Flash Card List</h2>

    {% if card_list %}
        
            
        {% for card in card_list %}
            {% comment %} <div id="flashCard{{ card.id }}" onclick="flipCard({{ card.id }})" class="card_front">
                <h1>
                    {{ card.front }}
                </h1>
            </div>
            <div id="flashCard{{ card.id }}" onclick="flipCard({{ card.id }})" class="card_back">
                <h1>
                    {{ card.back }} 
                </h1>
            </div> {% endcomment %}

            <div class="flip-card" id="flashCard{{ card.id }}" onclick="flipCard({{ card.id }})">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <h1> {{ card.front }} </h1>
                    </div>
                    <div class="flip-card-back">
                        <h1> {{ card.back }} </h1>
                    </div>
                </div>
            </div>

            <a href="delete/{{card.id}}">Delete</a>
        
        {% endfor %}

    {% else %}
    <p>No cards yet</p>

    {% endif %}

{% endblock %}

flash_cards_app/templates/flashcards/modal_layout.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
        </div>
    </div>
</div>

flash_cards_app/templates/flashcards/view_deck.html
{% extends "flashcards/layout.html" %}
{% block title %}
{{ deck.name }}
{% endblock %}
{% block content %}
<div style="display: flex; align-items: center; flex-direction: column; justify-content: center;">
  <div class="mt-3 mb-4">
    {% if deck %}
        <h1>{{ deck.name }}</h1>
    {% else %}
        <h1>No Deck</h1>
    {% endif %}
  </div>

  <button hx-get="{% url 'card_New' id=deck.id %}" hx-target="#dialog" class="btn btn-with-fa">
    <i class="fa-regular fa-square-plus"></i>New Card
  </button>

  <div class="big-padding" hx-get="{% url 'card_list' id=deck.id %}" hx-trigger="load, cardListChanged from:body" hx-target="this">
    <span>...Loading...</span>
  </div>
</div>

{% endblock %}